### ISSUE TITLE
Update the jjb templates to use workloads tooling

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift-scale/scale-ci-pipeline#4]
The templates for each scale test needs to be migrated to use workloads tooling and allow watcher to update the jobs on the Jenkins side.

**Comment by jmencak** [comment]
I wonder if this could this be done for all the jobs in one go, rather than each person trying to figure out what needs to be done?  Would it be possible to just create the PRs for us to review?  Thanks!

**Comment by chaitanyaenr** [comment]
All the jobs are using workloads tooling, closing the issue.
