### ISSUE TITLE
Simplify Job templates

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift-scale/scale-ci-pipeline#6]
There are couple of things in the Jobs which can be simplified like:
- Move and replace repos in the personal github namespace to openshift-scale organisation.
- Clone a repo with just the keys instead of cloning the entire perf-dept repo.
- Cleanup unused vars. 
- Add support to use workload tooling ( https://github.com/openshift-scale/scale-ci-pipeline/issues/4 )

**Comment by sjug** [comment]
https://github.com/openshift-scale/scale-ci-pipeline/pull/7 merged

**Comment by chaitanyaenr** [comment]
@sjug This issue covers the modifications we need to make on top of #7. Will keep updating the issue as we resolve them. Thanks.
