### ISSUE TITLE
R

### ISSUE THREAD

**Issue by abd45** [openshift-scale/scale-ci-pipeline#71]
R

**Comment by jtaleric** [comment]
ack - This is due to needing an ssh-key for our automation. The solution would be to make this a param that we pass, and to make this a non-disruptive change, default to `github.com/redhat-performance/perf-dept.git`

Any chance you are interested in contributing this change @abd45

**Comment by abd45** [comment]
@jtaleric I raised this issue from wrong account. I raised the same issue from my correct account. I am closing this issue. Thank you.
